/** DesireActionTypes */
export const SET_EXCEL_REQUEST = 'SET_EXCEL_REQUEST' as const;
export const SET_EXCEL_SUCCESS = 'SET_EXCEL_SUCCESS' as const;
export const SET_EXCEL_FAILURE = 'SET_EXCEL_FAILURE' as const;
export const SET_KEYINDEX_VALUE = 'SET_KEYINDEX_VALUE' as const;
export const USERLIST_SET_BY_FORMDATA_REQUEST = 'USERLIST_SET_BY_FORMDATA_REQUEST' as const;
export const USERLIST_SET_BY_FORMDATA_RESULT = 'USERLIST_SET_BY_FORMDATA_RESULT' as const;
export const MAILTEMPLATES_FETCH_REQUEST = 'MAILTEMPLATES_FETCH_REQUEST' as const;
export const MAILTEMPLATES_FETCH_SUCCESS = 'MAILTEMPLATES_FETCH_SUCCESS' as const;
export const MAILTEMPLATES_FETCH_FAILURE = 'MAILTEMPLATES_FETCH_FAILURE' as const;
export const MAILTEMPLATES_ALLFETCH_REQUEST = 'MAILTEMPLATES_ALLFETCH_REQUEST' as const;
export const MAILTEMPLATES_ALLFETCH_SUCCESS = 'MAILTEMPLATES_ALLFETCH_SUCCESS' as const;
export const MAILTEMPLATES_ALLFETCH_FAILURE = 'MAILTEMPLATES_ALLFETCH_FAILURE' as const;

/** MailActionTypes */
export const SET_MAIL_FORM = 'SET_MAIL_FORM' as const;
export const SET_MAIL_TEXT = 'SET_MAIL_TEXT' as const;
export const SET_MAIL_TITLE = 'SET_MAIL_TITLE' as const;
export const PUT_MAIL_FORM_REQUEST = 'PUT_MAIL_FORM_REQUEST' as const;
export const PUT_MAIL_FORM_SUCCESS = 'PUT_MAIL_FORM_SUCCESS' as const;
export const PUT_MAIL_FORM_FAILURE = 'PUT_MAIL_FORM_FAILURE' as const;
export const SET_MAIL_SELECTINDEX = 'SET_MAIL_SELECTINDEX' as const;
export const SET_MAIL_HEADIMAGE = 'SET_MAIL_HEADIMAGE' as const;
export const SET_MAIL_HEADIMAGE_URL = 'SET_MAIL_HEADIMAGE_URL' as const;
export const SET_ZIP_FILE = 'SET_ZIP_FILE' as const;
export const TOGGLE_MAIL_HEADIMAGE_EDIT_MODE = 'TOGGLE_MAIL_HEADIMAGE_EDIT_MODE' as const;
export const TOGGLE_MAIL_SUBIMAGE_EDIT_MODE = 'TOGGLE_MAIL_SUBIMAGE_EDIT_MODE' as const;
export const SET_MAIL_SUBIMAGE = 'SET_MAIL_SUBIMAGE' as const;
export const SET_MAIL_SUBIMAGE_URL = 'SET_MAIL_SUBIMAGE_URL' as const;

/** ExcelKeySetTypes */
export const SET_EXCEL_TEXT = 'SET_EXCEL_TEXT' as const;

/** RecruitTypes */
export const SET_RECRUIT_VALUE = 'SET_RECRUIT_VALUE' as const;
export const RECRUIT_DATA_REQUEST = 'RECRUIT_DATA_REQUEST' as const;
export const RECRUIT_DATA_SUCCESS = 'RECRUIT_DATA_SUCCESS' as const;
export const RECRUIT_DATA_FAILURE = 'RECRUIT_DATA_FAILURE' as const;
