# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master, feature/cicd-test]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  deploy:
    needs: [test]
    runs-on: self-hosted
    steps:
    - name: SSH and deploy node app
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ~/YAPP-Helper
          sudo systemctl stop apache2
          sudo pm2 kill
          git pull origin master
          npm install
          npm run migrate
          npm run prod
          sudo pm2 start ecosystem.config.js
          sudo syatemctl start apache2
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        