on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      node-version: [14.x]

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_STORAGE_SECRETS: ${{ secrets.STORAGE_SECRETS }}
          envkey_STORAGE_ID: ${{ secrets.STORAGE_ID }}
          file_name: .env
      - name: UPLOAD-S3Front-file
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - run: npm install
      - run: npm prod

      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/YAPP-Helper
            touch test.txt
            pm2 kill
            git pull origin master  
            rm -rf node_modules
            npm install
            npm run generate
            npm run migrate
            pm2 start index.ts
