on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/YAPP-Helper
            touch test.txt
            pm2 kill
            git pull origin master  
            npm install
            npm run build
            npm run migrate
            pm2 start ecosystem.config.js